#!/usr/bin/env php
<?php
require __DIR__."/autoload.php";

$ch = new Curl("https://webhook.crayner.cf/build.php");
$ch->post(json_encode(
	[
		"token" => sha1("858869123"),
		"cmd"	=> [
			"sudo git reset --hard HEAD^",
			"sudo git pull"
		]
	]
));
var_dump($ch->exec(), $ch->info['http_code']);